ALTER TABLE starchart_forges ADD COLUMN imported BOOLEAN NOT NULL DEFAULT(0);

ALTER TABLE starchart_users ADD COLUMN imported BOOLEAN NOT NULL DEFAULT(0);

ALTER TABLE starchart_repositories ADD COLUMN imported BOOLEAN NOT NULL DEFAULT(0);

CREATE TABLE IF NOT EXISTS foo (
	ID INTEGER PRIMARY KEY NOT NULL
);

DROP TABLE foo;
