log = "info" # possible values: "info", "warn", "trace", "error", "debug"
source_code = "https://github.com/forgeflux-org/starchart"
allow_new_index = true # allow registration on server
admin_email = "admin@starchart.example.com"

[server]
# The port at which you want authentication to listen to
# takes a number, choose from 1000-10000 if you dont know what you are doing
port = 7000
#IP address. Enter 0.0.0.0 to listen on all availale addresses
ip= "0.0.0.0" 
# enter your hostname, eg: example.com
domain = "localhost"
proxy_has_tls = false
cookie_secret = "f12d9adf4e364648664442b8f50bf478e748e1d77c4797b2ec1f56803278"
#workers = 2

[database]
# This section deals with the database location and how to access it
# Please note that at the moment, we have support for only postgresqa.
# Example, if you are Batman, your config would be:
# hostname = "batcave.org"
# port = "5432"
# username = "batman"
# password = "somereallycomplicatedBatmanpassword"
hostname = "localhost"
port = 5432
username = "postgres"
password = "password"
name = "postgres"
pool = 4
database_type = "postgres"

[crawler]
ttl = 432000 # of crawled records / how often the instance must be polled. In seconds.
items_per_api_call = 20
client_timeout = 60 # of HTTP client involved in crawling. In seconds.
wait_before_next_api_call = 2 # in seconds

[introducer]
#nodes = ["http://localhost:7000"]
nodes = []

[repository]
root = "/tmp/starchart.forgeflux.org"
